### ISSUE TITLE
Issue having hitting API

### ISSUE THREAD

**Issue by nihal0514** [dinushchathurya/nodejs-ecommerce-api#1]
I am not able to register, it is giving me 401 unauthorized ,"message": "The user is not authorized". please someone can help me ?

**Comment by dinushchathurya** [comment]
I have just tested it out but I couldn't able to fine any issue with the registration.

**Comment by nihal0514** [comment]
> I have just tested it out but I couldn't able to find any issue with the registration. 

message": "The user is not authorized"


How do  I pass authorization in register?

**Comment by dinushchathurya** [comment]
> > I have just tested it out but I couldn't able to find any issue with the registration. 
> 
> message": "The user is not authorized"
> 
> 
> How do  I pass authorization in register? 

Only you need to do is setup jwt secret in .env file, setup your mongodb string in database.config.js and then you can pass your data using registration endpoint.

**Comment by rakeshbhai0091** [comment]
> I have just tested it out but I couldn't able to find any issue with the registration.

hey man u done for isadmin if admin false then can make order etc then what use for it
